[package]
name = "rust_2048"


keywords=["2048", "cli", "game"]
version = "0.5.1"

license = "MIT"

[dependencies]
matrix_display = "0.3"
num = "0.1"
rand = "0.3"
termion = "1.2"

clippy = { version = "*", optional = true }

[features]
default = []
